### ISSUE TITLE
Need a way to enroll SDK identities with IDP authentication

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti#1352] opened 2023-06-26 15:50 UTC
Possibly have a stable JWT for each JWT signer with all needed information -- controller address, IDP URL, etc

**Comment by smilindave26** [comment] 2023-09-28 15:32
I'd like to include a flow where the user only needs to know a single URL, similar to what happens with BrowZer.  User can be handed that URL out-of-band.  When they hit it, the dance with IdP is kicked off.  Distributing that info in a JWT is a fine option, but hopefully not required.

**Comment by andrewpmartinez** [comment] 2024-08-21 13:48
Also see #2324

**Comment by andrewpmartinez** [comment] 2024-08-26 14:22
Closing as a dupe of: #2324

**Closed by andrewpmartinez** 2024-08-26 14:22 UTC
