### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jlin-nf** [openziti/ziti#895] opened 2022-11-11 03:05 UTC
ziti-router version 0.25.2

when query srv record via wild card dns service, the hosting ERT paniced.

On the WDE, perform the following command in powershelf:
> Resolve-DnsName zues.zitilocal.com -type SRV

On the hosting ERT:

Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: {"apiSessionId":"clabmql632jc0cgp242ioyyqd","attemptNumber":"1","binding":"edge","channels":["establishPath"],"circuitId":"XFHuMi9Vl","destination":"b61ddd3c-66ab-409d-8fb2-ef244296c745","file":"github.com/openziti/edge@v0.21.127/router/xgress_edge_tunnel/dialer.go:57","func":"github.com/openziti/edge/router/xgress_edge_tunnel.(*tunneler).Dial","level":"info","msg":"successful connection 10.12.1.2:60260-\u003e10.12.5.5:3389 for destination b61ddd3c-66ab-409d-8fb2-ef244296c745","sessionId":"clabmrrzp2jgccgp242mgtx21","time":"2022-11-11T01:12:39.474Z"}
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: {"apiSessionId":"cla8sm0b7y2hlcgp2j52w7107","attempt":2,"attemptNumber":"3","binding":"tunnel","channels":["establishPath"],"circuitId":"xdqAcw9Ve","context":"ch{ctrl}-\u003eu{reconnecting}-\u003ei{QV1gX}","destination":"901595a2-6f84-4dc5-b98c-d276894f8947","error":"error creating route for [c/xdqAcw9Ve]: dial tcp 10.12.14.16:65535: i/o timeout","file":"github.com/openziti/fabric@v0.17.62/router/handler_ctrl/route.go:122","func":"github.com/openziti/fabric/router/handler_ctrl.(*routeHandler).fail","level":"error","msg":"failed to connect egress","sessionId":"cla8smfupy2k6cgp20oq3rp12","time":"2022-11-11T01:12:39.508Z"}
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: {"file":"github.com/openziti/edge@v0.21.127/tunnel/intercept/hosting_resolv.go:79","func":"github.com/openziti/edge/tunnel/intercept.newResolvConn","level":"info","msg":"starting resolver connection","service":"zitilocal.com","time":"2022-11-11T01:12:39.960Z"}
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: {"apiSessionId":"clabsdogh2sapcgp24dpp2l40","attemptNumber":"1","binding":"edge","channels":["establishPath"],"circuitId":"Sq.VMwjVl","destination":"d4700b2c-f3a8-4a87-86cd-bbcb7b109980","file":"github.com/openziti/edge@v0.21.127/router/xgress_edge_tunnel/dialer.go:57","func":"github.com/openziti/edge/router/xgress_edge_tunnel.(*tunneler).Dial","level":"info","msg":"successful connection \u003cnil\u003e-\u003e\u003cnil\u003e for destination d4700b2c-f3a8-4a87-86cd-bbcb7b109980","sessionId":"clabszzqr2t9dcgp2vcc61zd8","time":"2022-11-11T01:12:39.960Z"}
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16123e2]
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: goroutine 1037 [running]:
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: github.com/openziti/edge/router/xgress_common.(*XgressConn).LogContext(0xc00014c000)
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]:         github.com/openziti/edge@v0.21.127/router/xgress_common/connection.go:130 +0x22
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: github.com/openziti/fabric/router/xgress.(*Xgress).rx(0xc0001eaf00)
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]:         github.com/openziti/fabric@v0.17.62/router/xgress/xgress.go:477 +0x192
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]: created by github.com/openziti/fabric/router/xgress.(*Xgress).payloadIngester
Nov 11 01:12:39 xxxx.yyyy.zzz ziti-router[2498212]:         github.com/openziti/fabric@v0.17.62/router/xgress/xgress.go:353 +0x212
Nov 11 01:12:40 xxxx.yyyy.zzz systemd[1]: ziti-router.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by plorenz** [comment] 2022-11-11 21:04
Duplicate of openziti/edge#1164

**Closed by plorenz** 2022-11-11 21:04 UTC
