### ISSUE TITLE
router run - ignores TERM and QUIT signals when unhappy

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1784] opened 2024-02-28 23:11 UTC
Only KILL (9) is effective at halting `ziti router run` in this scenario where its' trying to connect to the controller and getting a TLS error.

A happy router responds immediately to TERM (15) and QUIT (3) each with a graceful exit.

**Comment by dovholuknf** [comment] 2024-02-28 23:23
duplicate of https://github.com/openziti/ziti/issues/1755 maybe?

**Closed** 2024-02-29 00:01 UTC
