### ISSUE TITLE
Authentication with external JWTs triggers irrelevant error output

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#1690] opened 2024-01-18 15:41 UTC
*Experienced*

Authentication requests w/ a JWT in the `Authorization` header triggers the following output on every authentication request:

`ERROR ziti/controller/env.(*AppEnv).getJwtTokenFromRequest: {error=[token signature is invalid: key is of invalid type: ECDSA verify expects *ecsda.PublicKey]} error during JWT parsing during API request`

*Expected*
No error output. The code that triggers the error is meant for authenticated sessions. The session will never be authenticated in scenarios where it is attempting to authenticate with external JWTs.

*Reproduction*
Setup an external JWT signer and attempt to authenticate. The error output will occur on every authentication request.

Notes:
Use path matching to avoid filling the API Session information on authentication endpoints.

**Comment by rickwang7712** [comment] 2024-03-08 10:12
Hi,

I'm also facing similar error log after setting up Browzer & My First Service setup :
`[2055.884]   ERROR ziti/controller/env.(*AppEnv).getJwtTokenFromRequest: {error=[token signature is invalid: key is of invalid type: RSA verify expects *rsa.PublicKey]} error during JWT parsing during API request`

Is there any suggestion to workaround this? My controller's version is v0.32.2.
I have already confirmed the signature of Bearer token (jwt created from Auth0) in the request can be validated with Auth0's jwks manually.

Thank you very much!

**Comment by rickwang7712** [comment] 2024-03-14 07:58
Hi,

I finally found out that the problem I met should be the version problem, after I tried another version combination(v0.31.4 + browZer v0.49.1), all things work.

Thanks.

**Comment by dovholuknf** [comment] 2024-03-14 09:53
Thanks for following up. I'm not sure how we/i missed this issue, apologies for not seeing it. Since it sounds like you're all set I'll close the issue. Please reopen if necessary.

**Comment by smilindave26** [comment] 2024-09-18 15:19
Inadvertent re-open by Clint :)

**Closed by smilindave26** 2024-09-18 15:19 UTC
