### ISSUE TITLE
Missing variables from quickstart/default.env

### ISSUE THREAD

**Issue by RodneyRichardson** [openziti/ziti#690] opened 2022-04-20 13:48 UTC
I tried following the docker-compose example on Windows, but hit a couple of problems.

1. `docker-compose up` doesn't automatically pick up the default.env; I needed to use `docker-compose --env-file default.env up`.
2. ZITI_IMAGE and ZITI_VERSION variables are undefined; I added them to default.env, using `openziti/quickstart` and `latest` respectively.

Can the documentation and/or default.env files be updated acordingly?

**Comment by dovholuknf** [comment] 2022-04-20 14:25
Hi @RodneyRichardson ! Thanks for the issue. I personally haven't tested this on Windows but since someone else tried it, I'll give it a shot and update the doc. accordingly.

Right now, much of the doc will expect you to be running bash - usually in WSL because that's how I do it.

Just so I understand the ask here, would adding doc for powershell + docker be sufficient for you? That'd be me preference here.

And thanks for the issue. If you run into any other problems trying ziti out in windows please file other issues or post a topic in discourse.

**Comment by dovholuknf** [comment] 2022-04-20 14:48
Odd. I have never installed docker before on this machine. I just downloaded and installed it, then I changed to where the docker-compose file was on my local machine (which is from a clone of this repo) and ran `docker-compose up`. It ended up "just working" for me. I did not need to specify ZITI_IMAGE nor ZITI_VERSION because default.env was found...

```
docker ps -a
CONTAINER ID   IMAGE                        COMMAND                   CREATED         STATUS                       PORTS     NAMES
11608ae55b29   openziti/quickstart:latest   "/bin/bash /openziti…"    4 minutes ago   Exited (137) 3 minutes ago             docker-ziti-private-blue-1
566e40f83a2a   openziti/quickstart:latest   "/bin/bash /openziti…"    4 minutes ago   Exited (137) 3 minutes ago             docker-ziti-private-red-1
7500506f9d77   openziti/quickstart:latest   "/bin/bash /openziti…"    4 minutes ago   Exited (137) 3 minutes ago             docker-ziti-edge-router-wss-1
5cb84e0fefaf   openziti/quickstart:latest   "/bin/bash /openziti…"    4 minutes ago   Exited (137) 3 minutes ago             docker-ziti-fabric-router-br-1
4e01ab5ec4e0   openziti/quickstart:latest   "/bin/bash /openziti…"    4 minutes ago   Exited (137) 3 minutes ago             docker-ziti-edge-router-1
2cb2cf6573da   openziti/quickstart:latest   "/openziti/scripts/r…"    4 minutes ago   Exited (137) 2 minutes ago             docker-ziti-controller-1
b7a0025471c4   openziti/zac                 "docker-entrypoint.s…"    4 minutes ago   Exited (137) 3 minutes ago             docker-ziti-console-1
7fa9fff30aa1   crccheck/hello-world         "/bin/sh -c 'echo \"h…"   4 minutes ago   Exited (0) 3 minutes ago               docker-web-test-blue-1
7030f5dde753   hello-world                  "/hello"                  7 minutes ago   Exited (0) 7 minutes ago               magical_khorana                   
```

I even opened procmon up to verify docker-compose was searching for and opening default.env. You can even see that it followed the symlink properly:
![image](https://user-images.githubusercontent.com/46322585/164257594-45eace12-6179-4d50-b7fa-92f5043063db.png)

Perhaps your docker install is not up-to-date? Mine is brand new since I just installed it :) (Docker Desktop 4.7.1 (77678))

I did notice in my settings this setting "Use docker-compose V2" which was checked ON by default. Perhaps that's the difference?
![image](https://user-images.githubusercontent.com/46322585/164257962-8cf1bd5a-bf2a-435d-bf2b-aa9cb86ab5b7.png)

**Comment by dovholuknf** [comment] 2022-04-20 14:49
My docker environment also has ZAC running as well... I'm not sure there's anything for me to do here. If you can reproduce I'd be happy to update the doc.

![image](https://user-images.githubusercontent.com/46322585/164258344-bc23c9ac-dc60-4120-95bb-a05a97f180a0.png)

**Comment by dovholuknf** [comment] 2022-04-20 15:41
> Do you know where your variables are getting defined?
Well you are absolutely correct. They are not defined in there and I don't know why my `docker-compose up` worked. I'll have to scratch around and see if I can figure that out.

> the docker-compose.yml has a ziti-console service defined and so the Deployment Diagram for Docker Compose
yeah - probably should/could add the ZAC onto that diagram.

> Also, the paths to the certificates ... are wrong
I'll file an issue for this one. As you can guess from the screen cap I tend to use http when accessing ZAC deployed in docker but it should certainly support https. I'll file that issue

Thanks again

**Comment by RodneyRichardson** [comment] 2022-04-20 15:53
If I use the .env file instead, it works. Perhaps this just needs the documentation (https://openziti.github.io/ziti/quickstarts/network/local-docker-compose.html#preparation---required-files) to point to the .env file, not the default.env file?

**Comment by dovholuknf** [comment] 2022-04-20 16:03
Ah. My grep was ignoring the ".env" file which was why I wasn't finding where those variables were declared.  Yes - the doc needs to be updated to inform the user to grab the .env file now instead of the default.env and I agree. I'll remove default.env and all.localhost.env as well. I put that PR up just now https://github.com/openziti/ziti/pull/692

I updated the doc to point at ".env" too... https://github.com/openziti/ziti-doc/commit/54c2a29c55a9317ce21943c0bc8bc29ac6bc780a  that change should be pushed out to github pages in a moment

**Comment by RodneyRichardson** [comment] 2022-04-20 16:17
Brilliant. That seems sorted. I'm happy for this to be closed.

Do you want me to raise a separate issue about the Deployment Diagram not containing the ZAC/ziti-console? Or will you cover that in #691?

**Comment by dovholuknf** [comment] 2022-04-20 16:20
😉  https://github.com/openziti/ziti-doc/commit/e70929f9cde08aadb95dde09a0179fc4f1f230a6

**Comment by dovholuknf** [comment] 2022-04-20 16:22
diagram published. thanks. i'll close this issue https://openziti.github.io/ziti/quickstarts/network/docker-compose-overview.svg

**Closed by dovholuknf** 2022-04-20 16:22 UTC
Labels: documentation, enhancement

**Comment by RodneyRichardson** [comment] 2022-04-21 10:22
The `docker-compose.yml` file still refers to default.env:

https://github.com/openziti/ziti/blob/release-next/quickstart/docker/docker-compose.yml, line 6.

**Comment by dovholuknf** [comment] 2022-04-21 10:44
Thanks - I updated the PR and merged it just now. Line 6 now uses `.env`
